"""Symmetry-minimizing alignment between two trained models.

The relevant symmetry group of this architecture (ReLU MLP, no biases,
RMSNorm folded so gain=1) is generated by:

  (a) Permutation of attention heads inside a layer.
  (b) Per-head orthogonal rotation of the d_head subspace (V-O block).
      Applied as W_V <- R @ W_V (rotate output of V projection) and
      W_O <- W_O @ R^T (rotate input of O projection); cancels.
  (c) Per-head orthogonal rotation of the d_head subspace (Q-K block).
      Applied as W_Q <- R @ W_Q and W_K <- R @ W_K; cancels in Q @ K^T.
  (d) Permutation of MLP hidden neurons (rows of W_in / cols of W_out together).
  (e) Per-neuron positive scaling of MLP hidden units (W_in row by alpha,
      W_out col by 1/alpha; preserves ReLU output).
  (f) Orthogonal rotation R of the residual-stream basis: R @ residual.
      Applied across all weights that read from / write to the residual.
      Must be orthogonal because the (data-dependent) RMS scaling must be
      preserved -- RMSNorm commutes with O(d_model) but not with general GL.
  (g) Sign flips of attention heads' (V,O) subspace and per-row (Q,K).
      (These are special cases of (b)/(c) but combinatorial.)

This module implements a coordinate-descent search:
  -- Fix R = identity, find best permutations and scalings (closed form).
  -- Given current alignment, refine R via Procrustes on residual-stream
     weights (W_E, W_U, attention input/output projections concatenated).
  -- Alternate until parameter MSE stops decreasing.

This is not provably optimal, but in practice for trained Dyck transformers
it recovers the symmetry element to within numerical precision.
"""

from __future__ import annotations

import random

import torch
from scipy.optimize import linear_sum_assignment

from .model import Transformer


def _params_as_dict(model: Transformer) -> dict[str, torch.Tensor]:
    """Return a flat dict of param names -> tensors for alignment.

    Includes buffers (e.g. fixed positional encoding) since the residual
    rotation must transform them consistently with the parameters."""
    d = {}
    for name, p in model.named_parameters():
        d[name] = p.detach().clone()
    for name, b in model.named_buffers():
        if name == "W_pos":
            d[name] = b.detach().clone()
    return d


def _apply_residual_rotation(params: dict, R: torch.Tensor):
    """Rotate every operator that interacts with the residual stream by R.

    R has shape [d_model, d_model], orthogonal. The residual basis is rotated
    so that the new residual stream r' = R @ r.

      W_E[v, :]     -> W_E[v, :] @ R^T          (every token's embedding rotated)
      W_pos[t, :]   -> W_pos[t, :] @ R^T
      W_Q,K,V[..., :] -> W_Q,K,V[..., :] @ R^T  (each row reads residual; rotate input axis)
      W_O[h, :, p]  -> R @ W_O[h, :, p]         (write back to residual; rotate output axis)
      W_in[:, :]    -> W_in[:, :] @ R^T          (input projection of MLP)
      W_out[:, :]   -> R @ W_out[:, :]           (output projection of MLP)
      W_U_*[:, :]   -> W_U_*[:, :] @ R^T
      ln*.gain      -- only invariant under permutations & sign flips; for a
                       generic R the gain would need to be 1 (folded). We assume
                       caller has folded RMSNorm before invoking the search.
    """
    Rt = R.t()
    new = {}
    for k, v in params.items():
        if k == "W_E" or k == "W_pos":                  # [V, d]
            new[k] = v @ Rt
        elif k.endswith("attn.W_Q") or k.endswith("attn.W_K") or k.endswith("attn.W_V"):
            # [n_heads, d_head, d_model]; rotate last axis
            new[k] = torch.einsum("hpd,de->hpe", v, Rt)
        elif k.endswith("attn.W_O"):
            # [n_heads, d_model, d_head]; rotate dim 1 (output to residual)
            new[k] = torch.einsum("ed,hdp->hep", R, v)
        elif k.endswith("mlp.W_in"):
            # [d_mlp, d_model]; rotate last axis
            new[k] = v @ Rt
        elif k.endswith("mlp.W_out"):
            # [d_model, d_mlp]; rotate dim 0
            new[k] = R @ v
        elif k in ("W_U_tok", "W_U_depth", "W_U_valid"):
            # [n_out, d_model]; rotate last axis
            new[k] = v @ Rt
        elif k.endswith(".gain"):
            # rotation of an isotropic norm-gain only valid if gain == 1
            assert torch.allclose(v, torch.ones_like(v), atol=1e-4), \
                f"{k} not folded; cannot apply residual rotation."
            new[k] = v
        else:
            new[k] = v
    return new


def _apply_head_perm(params: dict, layer: int, perm: torch.Tensor):
    """Permute heads of `layer` according to perm (length n_heads)."""
    new = dict(params)
    for tag in ("attn.W_Q", "attn.W_K", "attn.W_V", "attn.W_O"):
        key = f"blocks.{layer}.{tag}"
        new[key] = params[key][perm]
    return new


def find_head_qk_rotation(p_seed: dict, p_ref: dict, layer: int, h: int) -> torch.Tensor:
    """Procrustes on the d_head axis of (W_Q | W_K) stacked.

    Returns R of shape [d_head, d_head] such that R @ W_Q[h] ~ W_Q_ref[h] and
    R @ W_K[h] ~ W_K_ref[h]. The transformation R applied to BOTH W_Q[h] and
    W_K[h] cancels in Q^T K (Q^T R^T R K = Q^T K for orthogonal R)."""
    Wq_s = p_seed[f"blocks.{layer}.attn.W_Q"][h]      # [d_head, d_model]
    Wk_s = p_seed[f"blocks.{layer}.attn.W_K"][h]
    Wq_r = p_ref[f"blocks.{layer}.attn.W_Q"][h]
    Wk_r = p_ref[f"blocks.{layer}.attn.W_K"][h]
    A = torch.cat([Wq_s, Wk_s], dim=1)                # [d_head, 2*d_model]
    B = torch.cat([Wq_r, Wk_r], dim=1)
    M = B @ A.t()                                      # [d_head, d_head]
    U, _, Vt = torch.linalg.svd(M.float())
    return (U @ Vt).to(A.dtype)


def find_head_vo_rotation(p_seed: dict, p_ref: dict, layer: int, h: int) -> torch.Tensor:
    """Procrustes on the d_head axis of (W_V | W_O^T) stacked.

    Applying R to W_V[h] (R @ W_V[h]) and R to W_O[h] on its d_head axis
    (W_O[h] @ R^T) leaves the head's contribution to the residual invariant:
    W_O[h] @ R^T @ R @ W_V[h] = W_O[h] @ W_V[h]."""
    Wv_s = p_seed[f"blocks.{layer}.attn.W_V"][h]      # [d_head, d_model]
    Wo_s = p_seed[f"blocks.{layer}.attn.W_O"][h].t()  # [d_head, d_model]
    Wv_r = p_ref[f"blocks.{layer}.attn.W_V"][h]
    Wo_r = p_ref[f"blocks.{layer}.attn.W_O"][h].t()
    A = torch.cat([Wv_s, Wo_s], dim=1)
    B = torch.cat([Wv_r, Wo_r], dim=1)
    M = B @ A.t()
    U, _, Vt = torch.linalg.svd(M.float())
    return (U @ Vt).to(A.dtype)


def _apply_head_qk_rotation(params: dict, layer: int, h: int, R: torch.Tensor):
    """Rotate (Q,K) of one head by R: W_Q[h] <- R @ W_Q[h], W_K[h] <- R @ W_K[h]."""
    new = dict(params)
    new[f"blocks.{layer}.attn.W_Q"] = params[f"blocks.{layer}.attn.W_Q"].clone()
    new[f"blocks.{layer}.attn.W_K"] = params[f"blocks.{layer}.attn.W_K"].clone()
    new[f"blocks.{layer}.attn.W_Q"][h] = R @ params[f"blocks.{layer}.attn.W_Q"][h]
    new[f"blocks.{layer}.attn.W_K"][h] = R @ params[f"blocks.{layer}.attn.W_K"][h]
    return new


def _apply_head_vo_rotation(params: dict, layer: int, h: int, R: torch.Tensor):
    """Rotate (V,O) of one head by R: W_V[h] <- R @ W_V[h], W_O[h] <- W_O[h] @ R^T."""
    new = dict(params)
    new[f"blocks.{layer}.attn.W_V"] = params[f"blocks.{layer}.attn.W_V"].clone()
    new[f"blocks.{layer}.attn.W_O"] = params[f"blocks.{layer}.attn.W_O"].clone()
    new[f"blocks.{layer}.attn.W_V"][h] = R @ params[f"blocks.{layer}.attn.W_V"][h]
    new[f"blocks.{layer}.attn.W_O"][h] = params[f"blocks.{layer}.attn.W_O"][h] @ R.t()
    return new


def _apply_mlp_perm(params: dict, layer: int, perm: torch.Tensor):
    """Permute MLP hidden neurons of `layer` according to perm (length d_mlp)."""
    new = dict(params)
    key_in = f"blocks.{layer}.mlp.W_in"
    key_out = f"blocks.{layer}.mlp.W_out"
    new[key_in] = params[key_in][perm]
    new[key_out] = params[key_out][:, perm]
    return new


def _apply_mlp_scaling(params: dict, layer: int, alphas: torch.Tensor):
    """Per-neuron positive scaling: W_in row by alpha, W_out col by 1/alpha."""
    new = dict(params)
    key_in = f"blocks.{layer}.mlp.W_in"
    key_out = f"blocks.{layer}.mlp.W_out"
    new[key_in] = params[key_in] * alphas.unsqueeze(1)
    new[key_out] = params[key_out] / alphas.unsqueeze(0)
    return new


def _param_mse(p1: dict, p2: dict, eps: float = 1e-12) -> float:
    """Total mean-squared error over all parameter tensors."""
    total_sq = 0.0; total_n = 0
    for k in p1:
        d = (p1[k] - p2[k]).flatten()
        total_sq += (d * d).sum().item()
        total_n += d.numel()
    return total_sq / max(total_n, 1)


def _max_per_tensor_mse(p1: dict, p2: dict) -> float:
    """Worst per-tensor mean-squared error (the quantity Bar P actually checks)."""
    max_m = 0.0
    for k in p1:
        d = (p1[k] - p2[k]).flatten()
        mse = float((d * d).mean().item())
        if mse > max_m:
            max_m = mse
    return max_m


def _hungarian(cost: torch.Tensor) -> torch.Tensor:
    """Return alignment permutation for `_apply_*_perm`.

    Hungarian returns col_ind such that cost[row_ind, col_ind].sum() is minimal,
    i.e. row r (seed-side index) is matched to col col_ind[r] (ref-side index).
    Our `_apply_*_perm(params, perm)` does `new[i] = params[perm[i]]`, so to put
    new[col_ind[r]] = params[r] (the seed head that matches ref slot col_ind[r])
    we need perm[col_ind[r]] = r -- i.e. the inverse of col_ind. For 2-cycles
    inv_col_ind == col_ind so this fix is a no-op on the previous codebase's
    observed alignments (head-0/head-1 swaps); for 3- and 4-cycles, this fix
    is required to correctly recover the symmetry element."""
    row_ind, col_ind = linear_sum_assignment(cost.detach().cpu().numpy())
    perm = torch.zeros(cost.shape[0], dtype=torch.long)
    for r, c in zip(row_ind, col_ind):
        perm[c] = r
    return perm


def find_head_perm(p_seed: dict, p_ref: dict, layer: int) -> torch.Tensor:
    """Find head permutation aligning seed to ref. Cost = sum over Q,K,V,O of
    Frobenius distance between candidate-head and ref-head matrices."""
    H = p_ref[f"blocks.{layer}.attn.W_Q"].shape[0]
    cost = torch.zeros(H, H)
    for hs in range(H):
        for hr in range(H):
            c = 0.0
            for tag in ("attn.W_Q", "attn.W_K", "attn.W_V", "attn.W_O"):
                a = p_seed[f"blocks.{layer}.{tag}"][hs]
                b = p_ref[f"blocks.{layer}.{tag}"][hr]
                c += ((a - b) ** 2).sum().item()
            cost[hs, hr] = c
    return _hungarian(cost)


def find_mlp_perm(p_seed: dict, p_ref: dict, layer: int) -> torch.Tensor:
    """Find MLP neuron permutation aligning seed to ref. Cost based on W_in rows
    and W_out cols simultaneously, normalised to be scale-invariant."""
    Win_s = p_seed[f"blocks.{layer}.mlp.W_in"]; Win_r = p_ref[f"blocks.{layer}.mlp.W_in"]
    Wout_s = p_seed[f"blocks.{layer}.mlp.W_out"].t(); Wout_r = p_ref[f"blocks.{layer}.mlp.W_out"].t()
    # Combine row signatures
    sig_s = torch.cat([Win_s, Wout_s], dim=1)        # [d_mlp, 2*d_model]
    sig_r = torch.cat([Win_r, Wout_r], dim=1)
    # Cosine cost: 1 - cos(sig_s_i, sig_r_j)
    sig_s_n = sig_s / (sig_s.norm(dim=1, keepdim=True) + 1e-9)
    sig_r_n = sig_r / (sig_r.norm(dim=1, keepdim=True) + 1e-9)
    cost = 1.0 - sig_s_n @ sig_r_n.t()
    return _hungarian(cost)


def find_mlp_scaling(p_seed: dict, p_ref: dict, layer: int) -> torch.Tensor:
    """Closed-form per-neuron positive scaling that minimises mismatch.

    For each neuron i, we choose alpha_i > 0 to minimise
        || alpha_i * w_in_i - w_in_ref_i ||^2 + || (1/alpha_i) * w_out_i^T - w_out_ref_i^T ||^2.
    Setting derivative to zero gives a 4th-order polynomial; we use the
    geometric-mean heuristic: alpha = sqrt(||w_in_ref|| ||w_out_seed|| /
                                            ||w_in_seed|| ||w_out_ref||).
    """
    Win_s = p_seed[f"blocks.{layer}.mlp.W_in"]; Win_r = p_ref[f"blocks.{layer}.mlp.W_in"]
    Wout_s = p_seed[f"blocks.{layer}.mlp.W_out"].t(); Wout_r = p_ref[f"blocks.{layer}.mlp.W_out"].t()
    nin_s = Win_s.norm(dim=1); nin_r = Win_r.norm(dim=1)
    nout_s = Wout_s.norm(dim=1); nout_r = Wout_r.norm(dim=1)
    alpha = torch.sqrt((nin_r * nout_s).clamp(min=1e-12) / (nin_s * nout_r).clamp(min=1e-12))
    return alpha.clamp(min=1e-4, max=1e4)


def find_residual_rotation(p_seed: dict, p_ref: dict) -> torch.Tensor:
    """Procrustes alignment of residual-stream basis.

    Constructs concatenated matrices of all residual-touching parameters and
    finds the orthogonal R that minimises ||(M_seed @ R) - M_ref||_F."""
    # Concatenate things that read FROM residual stream (rows are residual-basis)
    pieces_seed, pieces_ref = [], []
    # W_E [V, d] each row is residual
    pieces_seed.append(p_seed["W_E"]); pieces_ref.append(p_ref["W_E"])
    pieces_seed.append(p_seed["W_pos"]); pieces_ref.append(p_ref["W_pos"])
    n_layers = sum(1 for k in p_ref if k.startswith("blocks.") and k.endswith(".attn.W_Q"))
    for L in range(n_layers):
        # W_Q,K,V have residual in last axis
        for tag in ("attn.W_Q", "attn.W_K", "attn.W_V"):
            t = p_seed[f"blocks.{L}.{tag}"].reshape(-1, p_seed[f"blocks.{L}.{tag}"].shape[-1])
            r = p_ref[f"blocks.{L}.{tag}"].reshape(-1, p_ref[f"blocks.{L}.{tag}"].shape[-1])
            pieces_seed.append(t); pieces_ref.append(r)
        # W_O has residual on dim 1 (the "output" axis written back). For the
        # Procrustes side we need vectors in d_model space; treat each (head, head_dim)
        # column as one such vector.
        Wo_s = p_seed[f"blocks.{L}.attn.W_O"]
        Wo_r = p_ref[f"blocks.{L}.attn.W_O"]
        # reshape [H, d_model, d_head] -> [H*d_head, d_model]
        Wo_s = Wo_s.permute(0, 2, 1).reshape(-1, Wo_s.shape[1])
        Wo_r = Wo_r.permute(0, 2, 1).reshape(-1, Wo_r.shape[1])
        pieces_seed.append(Wo_s); pieces_ref.append(Wo_r)
        # MLP W_in last axis residual; W_out first axis residual
        pieces_seed.append(p_seed[f"blocks.{L}.mlp.W_in"]); pieces_ref.append(p_ref[f"blocks.{L}.mlp.W_in"])
        pieces_seed.append(p_seed[f"blocks.{L}.mlp.W_out"].t()); pieces_ref.append(p_ref[f"blocks.{L}.mlp.W_out"].t())
    for tag in ("W_U_tok", "W_U_depth", "W_U_valid"):
        pieces_seed.append(p_seed[tag]); pieces_ref.append(p_ref[tag])

    M_s = torch.cat(pieces_seed, dim=0)        # [N, d_model]
    M_r = torch.cat(pieces_ref, dim=0)
    # Procrustes: R = V @ U^T where M_s.T @ M_r = U @ S @ V^T
    # Want: ||(M_s @ R) - M_r|| minimal, R orthogonal
    A = M_s.t() @ M_r                           # [d_model, d_model]
    U, _, Vt = torch.linalg.svd(A.float())
    R = (U @ Vt).t()                             # since we want M_s @ R ≈ M_r
    # The transposed convention: A = M_s^T M_r = U S V^T. To minimise
    # ||M_s R - M_r||^2 with R orthogonal, the closed form is R = U V^T.
    R = (U @ Vt)
    return R


def _single_align_run(p_seed0: dict, p_ref: dict, n_layers: int,
                       start_perms: list[torch.Tensor], n_outer: int,
                       use_residual_rotation: bool = True) -> tuple[dict, dict]:
    """Run one alignment trajectory from a specific starting head permutation per layer.

    The coordinate-descent steps are not strictly monotonic in MSE (a residual
    rotation that helps one tensor may hurt another), so we track the best
    state across all iterations and return that, not the last."""
    p_seed = dict(p_seed0)
    for L, perm in enumerate(start_perms):
        p_seed = _apply_head_perm(p_seed, L, perm)
    info = {"head_perms": [perm.tolist() for perm in start_perms],
            "mlp_perms": [], "mlp_scales": [], "residual_R": None,
            "head_qk_R": [[] for _ in range(n_layers)],
            "head_vo_R": [[] for _ in range(n_layers)],
            "mse_history": [_param_mse(p_seed, p_ref)],
            "start_perms": [perm.tolist() for perm in start_perms]}

    # Track by MAX per-tensor MSE (the quantity Bar P checks) AND by total MSE.
    # Use max as primary — this prevents the residual rotation from inflating
    # one frozen-shared tensor (e.g., W_U_tok) to "improve" sum-MSE.
    best_mse = info["mse_history"][0]
    best_max = _max_per_tensor_mse(p_seed, p_ref)
    info["max_history"] = [best_max]
    best_p = dict(p_seed)
    best_info_snapshot = dict(info)
    best_info_snapshot["head_perms"] = list(info["head_perms"])

    def _maybe_track_best():
        nonlocal best_mse, best_max, best_p, best_info_snapshot
        cur_sum = info["mse_history"][-1]
        cur_max = _max_per_tensor_mse(p_seed, p_ref)
        info["max_history"].append(cur_max)
        # Prefer (lower max, lower sum) ordering.
        if (cur_max, cur_sum) < (best_max, best_mse):
            best_mse = cur_sum; best_max = cur_max
            best_p = dict(p_seed)
            best_info_snapshot = {
                "head_perms": list(info["head_perms"]),
                "mlp_perms": list(info["mlp_perms"]),
                "mlp_scales": list(info["mlp_scales"]),
                "residual_R": info["residual_R"],
                "head_qk_R": [list(x) for x in info["head_qk_R"]],
                "head_vo_R": [list(x) for x in info["head_vo_R"]],
            }

    for outer in range(n_outer):
        # 1) residual rotation (skipped when use_residual_rotation=False;
        # this is the right setting when the residual basis is already
        # aligned across seeds — e.g. when I/O weights are frozen-shared
        # under Fix E).
        if use_residual_rotation:
            R = find_residual_rotation(p_seed, p_ref)
            p_seed = _apply_residual_rotation(p_seed, R)
            info["residual_R"] = R if info["residual_R"] is None else (R @ info["residual_R"])
            info["mse_history"].append(_param_mse(p_seed, p_ref))
            _maybe_track_best()
        # 2) per layer
        for L in range(n_layers):
            # Head permutation
            hp = find_head_perm(p_seed, p_ref, L)
            p_seed = _apply_head_perm(p_seed, L, hp)
            info["head_perms"][L] = hp.tolist()
            info["mse_history"].append(_param_mse(p_seed, p_ref))
            _maybe_track_best()
            # Per-head QK/VO rotations
            H = p_seed[f"blocks.{L}.attn.W_Q"].shape[0]
            for h in range(H):
                Rqk = find_head_qk_rotation(p_seed, p_ref, L, h)
                p_seed = _apply_head_qk_rotation(p_seed, L, h, Rqk)
                Rvo = find_head_vo_rotation(p_seed, p_ref, L, h)
                p_seed = _apply_head_vo_rotation(p_seed, L, h, Rvo)
                if outer == 0:
                    info["head_qk_R"][L].append(Rqk.tolist())
                    info["head_vo_R"][L].append(Rvo.tolist())
                else:
                    info["head_qk_R"][L][h] = Rqk.tolist()
                    info["head_vo_R"][L][h] = Rvo.tolist()
            info["mse_history"].append(_param_mse(p_seed, p_ref))
            _maybe_track_best()
            # MLP permutation & scaling
            mp = find_mlp_perm(p_seed, p_ref, L)
            p_seed = _apply_mlp_perm(p_seed, L, mp)
            sc = find_mlp_scaling(p_seed, p_ref, L)
            p_seed = _apply_mlp_scaling(p_seed, L, sc)
            if outer == 0:
                info["mlp_perms"].append(mp.tolist())
                info["mlp_scales"].append(sc.tolist())
            else:
                info["mlp_perms"][L] = mp.tolist()
                info["mlp_scales"][L] = sc.tolist()
            info["mse_history"].append(_param_mse(p_seed, p_ref))
            _maybe_track_best()

    info["best_mse"] = best_mse
    info["best_max_mse"] = best_max
    for k in ("head_perms", "mlp_perms", "mlp_scales", "residual_R",
              "head_qk_R", "head_vo_R"):
        if k in best_info_snapshot:
            info[k] = best_info_snapshot[k]

    return best_p, info


def align(model_seed: Transformer, model_ref: Transformer,
          n_outer: int = 6, n_starts: int = 16,
          rng_seed: int = 0,
          try_no_rotation: bool = True) -> tuple[dict, dict]:
    """Multi-start coordinate-descent alignment of `model_seed` to `model_ref`.

    Args:
      n_outer: inner coordinate-descent iterations per start.
      n_starts: number of random head-permutation start points (1st is identity).
      try_no_rotation: also include runs with the residual rotation step
        disabled, which helps when the residual basis is already aligned
        (e.g., under Fix E with frozen shared I/O).

    Returns (aligned_params, alignment_info).
    """
    p_seed0 = _params_as_dict(model_seed)
    p_ref = _params_as_dict(model_ref)
    n_layers = sum(1 for k in p_ref if k.startswith("blocks.") and k.endswith(".attn.W_Q"))
    H = p_ref["blocks.0.attn.W_Q"].shape[0]

    rng = random.Random(rng_seed)
    starts = [[torch.arange(H) for _ in range(n_layers)]]
    for _ in range(n_starts - 1):
        starts.append([
            torch.tensor(rng.sample(range(H), H), dtype=torch.long)
            for _ in range(n_layers)
        ])

    best_max = float("inf"); best_mse = float("inf")
    best_p, best_info = None, None
    all_best_max = []; all_best_mse = []
    rotation_modes = [True, False] if try_no_rotation else [True]
    for use_rot in rotation_modes:
        for si, start_perms in enumerate(starts):
            p_aligned, info = _single_align_run(p_seed0, p_ref, n_layers,
                                                 start_perms, n_outer,
                                                 use_residual_rotation=use_rot)
            cand_max = info.get("best_max_mse", _max_per_tensor_mse(p_aligned, p_ref))
            cand_sum = info.get("best_mse", info["mse_history"][-1])
            all_best_max.append(cand_max); all_best_mse.append(cand_sum)
            if (cand_max, cand_sum) < (best_max, best_mse):
                best_max = cand_max; best_mse = cand_sum
                best_p = p_aligned; best_info = info
                best_info["best_start_index"] = si
                best_info["best_use_rotation"] = use_rot

    if best_info is not None:
        best_info["all_best_max_mse"] = all_best_max
        best_info["all_best_mse"] = all_best_mse
        best_info["n_starts"] = n_starts

    return best_p, best_info
